// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using la_mia_pizzeria_post.Data;

#nullable disable

namespace la_mia_pizzeria_post.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221005115038_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("la_mia_pizzeria_static.Models.Pizza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.HasKey("Id");

                    b.ToTable("Pizzas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "La classica pizza",
                            Name = "Margherita",
                            Photo = "margherita.png",
                            Price = 4.00m
                        },
                        new
                        {
                            Id = 2,
                            Description = "La classica pizza piccante",
                            Name = "Diavola",
                            Photo = "diavola.png",
                            Price = 5.50m
                        },
                        new
                        {
                            Id = 3,
                            Description = "La classica pizza con prosciutto cotto",
                            Name = "Cotto",
                            Photo = "cotto.png",
                            Price = 5.00m
                        },
                        new
                        {
                            Id = 4,
                            Description = "La classica pizza con la salsiccia",
                            Name = "Salsiccia",
                            Photo = "salsiccia.png",
                            Price = 6.50m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
